development:
  adapter: postgresql
  encoding: unicode
  database: LP72_development
  pool: 5
  username: postgres
  password: julien

test:
  adapter: postgresql
  encoding: unicode
  database: LP72_test
  pool: 5
  username: postgres
  password: julien

production:
  adapter: postgresql
  encoding: unicode
  database: LP72_production
  pool: 5
  username: postgres
  password: julien